name: TheTrade
version: '1.0-PRE'
main: com.gamegamerstudios.theTrade.Plugin
api-version: '1.8'
authors: [ GameGamerStudios ]
description: The best item-trading solution.
depend: [Vault]
commands:
  trade:
    usage: /trade <player>
    description: Trade items and currency with other players.
    permission: thetrade.trade
  tradeadmin:
    usage: /tradeadmin help
    description: See who is currently trading, prevent a player from trading, so much more!
    permission: thetrade.admin
    aliases:
      - ta
      - tradea
permissions:
  thetrade.trade:
    description: Allows a player to trade with other players (/trade)
    default: true
  thetrade.admin:
    description: The admin permission for TheTrade.
    default: op
    children:
      - thetrade.bypassradius
  thetrade.bypassradius:
    default: op
    description: Bypass the trading radius.